### ISSUE TITLE
atLeast and atMost together makes the parser hang

### ISSUE THREAD

**Issue by EyeCon** [KatrinaKitten/honeycomb#3]
I expected to be able to parse a (non-delimited) group of digits, grouped into some clusters. as follows:

`digit.atMost(3).atLeast(4).parse("255314")`

As a result, I expected a grouping of the digit clusters like "2", "5","53","14"; but the parser hangs (or at least, runs for 5 minutes without any result).

**Environment:**
 - OS: Windows amd64
 - Nim version: 1.7.1 (devel)

**Additional context**
I am a new user and might be missing something. If so, a pointer would be appreciated, as well as any other way to achieve what I'm trying to do.

**Comment by kgscialdone** [comment]
Thanks for the report! This is *somewhat* intentional, but imperfectly implemented. All parsers offered by default in Honeycomb are greedy, meaning they'll consume as much input as they can successfully match, and they also can't backtrack if a later parser in the chain fails as a result of that greediness. What's happening here is `atMost(3)` consumes 3, then `atLeast(4)` kicks in causing it to consume another 3, and then it runs out of input. I'll put it on my TODO list to implement some way of creating non-greedy parsers for use cases like this.

What definitely *is* a bug is the hanging as a result, which I'll look into ASAP. I most likely screwed up a while loop condition in the implementation of `times(Slice[int])`, which `atLeast(4)` running out of input in this particular way uncovered.

**Comment by kgscialdone** [comment]
Issue confirmed, it results from [this line](https://github.com/KatrinaKitten/honeycomb/blob/master/honeycomb.nim#L534) as expected. `atLeast` is implemented as `times(n..high(int))` and `atMost` as `times(0..n)`, resulting in a loop that attempts to run billions of times and never breaks since `atMost` always succeeds even with no input remaining. Needs analysis to determine the best way to prevent this.
